[project]
name = "riddle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ablog>=0.11.12",
    "parsy>=2.2",
    "pydata-sphinx-theme>=0.16.1",
    "sphinx>=8.2.3",
    "sphinxcontrib-youtube>=1.4.1",
]
